sano_blog:
    resource: "@SanoBlogBundle/Controller/"
    type:     annotation
    prefix:   /blog

_static:
    pattern:  /
    defaults: { _controller: SanoStaticBundle:default:index }

sanoNewsBundle:
    resource: "@SanoNewsBundle/Controller/"
    type:     annotation
    prefix:   /news

SanoStaticBundle:
    resource: "@SanoStaticBundle/Controller/"
    prefix:   /

#AcmeAdminBundle:
 #   resource: "@AcmeAdminBundle/Resources/config/routing.yml"
  #  prefix:   /admin
   
#AdminController:
 #   resource: "@AcmeAdminBundle/Controller/DefaultController.php"
  #  type:     annotation
    
#WelcomeController:
 #   resource: "@AcmeDemoBundle/Controller/WelcomeController.php"
  #  type:     annotation

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

