<?php

namespace Sano\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT p FROM SanoBlogBundle:post p ORDER BY p.creation_date DESC')
                    ->getResult();
    }
    public function getArchive($year, $month)
    {
        $fromDay = new \DateTime("$year-$month-01");
        $toDay = clone $fromDay;
        $toDay->add(new \DateInterval('P1M'));

        return $this->getEntityManager()
                            ->createQuery("SELECT n FROM SanoBlogBundle:post n
                                            WHERE n.creation_date >= :minDate
                                                AND n.creation_date < :maxDate
                                            ORDER BY n.creation_date DESC")
                            ->setParameters(array(
                                            'minDate' => $fromDay,
                                            'maxDate'  => $toDay,
                                            ))
                            ->getResult();
    }
    public function getYearsAndMonths($limit)
    {
         return $this->getEntityManager()
                     ->createQuery("SELECT YEAR(p.creation_date) AS year, DATE_FORMAT(p.creation_date, '%M') AS month, p.creation_date AS creation_date
                                    FROM SanoBlogBundle:post p  
                                    GROUP BY year, month")
                     ->setMaxResults($limit)
                     ->getResult();
    }

}
