<?php

namespace Sano\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT n FROM SanoNewsBundle:news n ORDER BY n.creation_date DESC')
                    ->getResult();
    }
    
    public function findAllActive($limit)
    {
        return $this->getEntityManager()
                    ->createQuery("SELECT n FROM SanoNewsBundle:news n 
                                    WHERE n.status = 'active'
                                    ORDER BY n.creation_date DESC")
                    ->setMaxResults($limit)
                    ->getResult();
    }
    public function getArchive($year, $month)
    {
        $minDate = date("Y-m-d H:i:s", mktime(0,0,0,$month,1,$year));   //minimalna mejna vrednost, the MySQL DATETIME format
        $maxDate = new \DateTime($minDate);             //maximalna mejna vrednost, 
        $maxDate->add(new \DateInterval("P1M"));        //interval 1 mesec
        $maxDate->format('Y-m-d H:i:s');                //the MySQL DATETIME format

        return $this->getEntityManager()
                    ->createQuery("SELECT n FROM SanoNewsBundle:news n 
                                    WHERE n.creation_date > :minDate 
                                        AND n.creation_date < :maxDate
                                    ORDER BY n.creation_date DESC")
                    ->setParameters(array(
                                    'minDate' => $minDate,
                                    'maxDate'  => $maxDate,
                                    ))
                    ->getResult();
    }
}
